# -*- coding: utf-8 -*-
"""LinearRegressionAlgorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19WMJJ5s0D8vRt5CKxcEg9H0rPvawp30Q
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('homeprices.csv')
df

x = df.iloc[:,0:1] #specific first column
y = df.iloc[:,-1:-2:-1]

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(x,y)

model.predict([[3300]])

model.coef_

model.intercept_

#y=mx+c
135.78767123*3300+180616.43835616

####Another way of predicting data

df2 = pd.read_csv('Salary_Data.csv')

x= df2.iloc[:,0:1]
y= df2.iloc[:,-1:-2:-1]

x

y

from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=0)

x_train

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

y_pred= model.predict(x_test)

y_test

model.score(x_test,y_test) # to test accuracy score

from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

