# -*- coding: utf-8 -*-
"""web_scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14NcwnzZeqM3J8Q2xSA_2UcyamWLJJt9P
"""

from bs4 import BeautifulSoup

import requests

URL="https://www.monster.com/jobs/search/?q=Software-Developer&where=Australia"

page = requests.get(URL)

soup = BeautifulSoup(page.content, 'html.parser')

soup

result = soup.find(id='ResultsContainer')

result

job_elements= result.find_all('section',class_='card-content')

for i in job_elements:
  print(i)

for i in job_elements:
  title= i.find('h2', class_='title')
  company = i.find('div', class_='company')
  location = i.find('div',class_='location')
  if None in (title,company, location):
    continue
  print(title.text)
  print(company.text)
  print(location.text)

import pandas as pd

df=pd.DataFrame({
    'title': title.text,
    'company': company.text,
    'location': location.text
})

title

title.text

typeof(title)

type(title)

title=[]
company=[]
location=[]

for i in job_elements:
  t= i.find('h2', class_='title')
  c = i.find('div', class_='company')
  l= i.find('div',class_='location')
  if None in (t,c, l):
    continue
  title.append(t.text)
  company.append(c.text)
  location.append(l.text)

df = pd.DataFrame({
    'title':title,
    'company':company,
    'location':location
})
df

